config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'
  get 'welcome/index'
  
  root 'welcome#index'

  devise_for :users
  resources :lists
  resources :responsibles
  resources :teams
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
end

app/models/team.rb
class Team < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:developer, :responsible]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  belongs_to :team  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pundit
    before_action :configure_permitted_parameters, if: :devise_controller?

    #def configure_permitted_parameters
    #    devise_parameter_sanitizer.permit(:sign_up, keys: [:team_id])
    #    devise_parameter_sanitizer.permit(:account_update, keys: [:team_id])
    #end

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:role, :team_id, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:role, :team_id, :email, :password, :current_password)}
    end

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    private

    def user_not_authorized
        flash[:alert] = "No permition!"
        redirect_to(request.referrer || root_path)
    end
end

app/controllers/control_users_controller.rb
class ControlUsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user! ,except[:index]
  before_action :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    #@lists = List.all

    # Validate the user role: if developer then filter only lists created by himself
    #                         else filter all lists created by users who belongs to his team
    if current_user.role == "developer"
      
      @lists = List.where(user_id: current_user.id).order('id DESC')
      #@user = User.where(id: @lists.first.user_id).take
      #@team = Team.where(id: @user.team_id).take
    
    else
    
      #@lists = List.all
      
      @users = User.where(team_id: current_user.team.id).all
      
      @users.each do |user|
         @lists = List.where(user_id: User.where(team_id: current_user.team.id).all)
      end
      
      @lists.each do |list|
        @users_mail = User.where(id: list.user_id).take.email
      end
      
      @team = Team.where(id: current_user.team.id).take

    end

  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:today, :yesterday, :impediment, :user_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /teams
  # GET /teams.json
  def index
    @teams = Team.all
    @users = User.all
    authorize @users
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams
  # POST /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1
  # PATCH/PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy
    respond_to do |format|
      format.html { redirect_to teams_url, notice: 'Team was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_params
      params.require(:team).permit(:name, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_users_helper.rb
module ControlUsersHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/control_users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:role) %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    
    <title><%= content_for?(:title) ? yield(:title) : "Dailys" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Dailys</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Shortcuts</h3>
            <% if user_signed_in? %>
              <ul class="nav nav-list">
                <p class="text-muted"><%= "User: " + current_user.email %></p>
                <p><%= link_to "Sair", destroy_user_session_path, method: :delete %> / <%= link_to "Editar", edit_user_registration_path %></p>
              </ul>
            <% else %>
              <ul class="nav nav-list">
                <li><%= link_to "Login", new_user_session_path %></li>
                <li><%= link_to "New user", new_user_registration_path %></li>
              </ul>
            <% end %>

            <ul class="nav nav-list">
              <% if current_user %>
                <% if current_user.role == "responsible" %>
                  <li><%= link_to "Teams", teams_path %></li>
                  <li><%= link_to "Users", control_users_index_path  %></li>
                  <li><%= link_to "Lists", lists_path  %></li>
                <% else %>
                  <li><%= link_to "Lists", lists_path  %></li>
                <% end %>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Desafio 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, :html => { :class => "form-horizontal list" } do |f| %>

  <% if @list.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :today, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :today, :class => 'form-control' %>
    </div>
    <%=f.error_span(:today) %>
  </div>
  <div class="form-group">
    <%= f.label :yesterday, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :yesterday, :class => 'form-control' %>
    </div>
    <%=f.error_span(:yesterday) %>
  </div>

  <div class="form-group">
    <%= f.label :impediment, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :impediment, :class => 'btn' %>
    </div>
    <%=f.error_span(:impediment) %>
  </div>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                lists_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:today) %></th>
      <th><%= model_class.human_attribute_name(:yesterday) %></th>
      <th><%= model_class.human_attribute_name(:impediment) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:team) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list, index| %>
      <tr>
        <td><%= link_to list.id, list_path(list) %></td>
        <td><%= list.today %></td>
        <td><%= list.yesterday %></td>
        <td><%= list.impediment %></td>
        <td><%= User.where(id: list.user_id).take.email %></td>
        <td><%= @team.name %></td>
        <td><%= list.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      list_path(list), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_list_path(list), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      list_path(list),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_list_path,
            :class => 'btn btn-primary' %>

app/views/lists/new.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/lists/show.html.erb
<%- model_class = List -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:today) %>:</strong></dt>
  <dd><%= @list.today %></dd>
  <dt><strong><%= model_class.human_attribute_name(:yesterday) %>:</strong></dt>
  <dd><%= @list.yesterday %></dd>
  <dt><strong><%= model_class.human_attribute_name(:impediment) %>:</strong></dt>
  <dd><%= @list.impediment %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @list.user_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              lists_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_list_path(@list), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              list_path(@list),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_password) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_token, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_token, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_token) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_sent_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_sent_at) %>
  </div>
  <div class="form-group">
    <%= f.label :remember_created_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :remember_created_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:remember_created_at) %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_sign_in_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_sign_in_at) %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_sign_in_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_sign_in_at) %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_sign_in_ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_sign_in_ip) %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_sign_in_ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_sign_in_ip) %>
  </div>
  <div class="form-group">
    <%= f.label :team_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :team_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:team_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:team_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%= user.team_id %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:team_id) %>:</strong></dt>
  <dd><%= @user.team_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<!--h1>Dailys</h1-->
<p>Welcome!</p>

<!--
<% if user_signed_in? %>
    <ul class="nav nav-list">
        <li>Logado como:  <%= current_user.email %> </li>
        <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Editar", edit_user_registration_path %></li>

    </ul>
<% else %>
    <ul class="nav nav-list">
        <li><%= link_to "Cad. Usuários", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
    </ul>
<% end %>

<ul>
    <li><%= link_to "Responsáveis", responsibles_path %></li>
    <li><%= link_to "Equipes", teams_path %></li>
    <li><%= link_to "Listas", lists_path  %></li>
</ul>
-->